resources:
  - name: dockerbuild_repo
    type: GitRepo
    configuration:
      path: skylark05/dockerbuild
      gitProvider: github
      
pipelines:
  - name: docker_example
    steps:
      - name: build_docker
        type: DockerBuild
        configuration:
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: mill.jfrog.info:12052/docker/ragesh
          dockerImageTag: $pipeline_name.$run_number
          inputResources:
            - name: dockerbuild_repo
          integrations:
            - name: art
      - name: push_docker_image
        type: PushArtifactoryPackage
        configuration:
          targetRepo: docker
          integrations:
            - name: art
          inputSteps:
            - name: build_docker

