resources:
  - name: artifactory_go_example
    type: GitRepo
    configuration:
      path: skylark05/artifactory-go-example
      gitProvider: github
 
pipelines:
  - name: go_example_build
    steps:
      - name: build
        type: GoBuild
        configuration:
          sourceLocation: .
          repository: go
          outputLocation: /tmp
          outputFile: hello
          inputResources:
            - name: artifactory_go_example
          integrations:
            - name: art
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
       
