resources:
  - name: artifactory_go_example
    type: gitRepo
    repoPath: skylark05/artifactory-go-example
    configuration:
      integrationName: github
    version:
      sha: master
  - name: some_file
    type: file
    configuration:
      integrationName: art
    version:
      fileLocation: ragesh-generic
      fileName: foo.txt
 
pipelines:
  - name: go_example_build
    steps:
      - name: build
        type: GoBuild
        configuration:
          sourceLocation: .
          repository: go
          outputLocation: /tmp
          outputFile: hello
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
        requires:
          resources:
            - artifactory_go_example
            - some_file
          integrations:
            - art
      - name: push
        type: push
        setup:
          push:
            targetRepo: ragesh-generic
        requires:
          integrations:
            - art
        triggeredBy:
          steps:
            - build
