resources:
  - name: artifactory_go_example
    type: GitRepo
    configuration:
      path: deepikasl/artifactory-go-example
      gitProvider: deepikaGithub
 
pipelines:
  - name: go_example_publish
    steps:
      - name: publish_go
        type: GoPublish
        configuration:
          sourceLocation: .
          version: v1.2.0
          targetRepository: deepika-go
          deps: all
          inputResources:
            - name: artifactory_go_example
          integrations:
            - name: deepika_artifactory
        execution:
          onStart:
            - wget https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
            - sudo tar -C /usr/local -xzf go1.12.5.linux-amd64.tar.gz
            - export PATH=$PATH:/usr/local/go/bin
            - go version
     
