resources:
  - name: build_info_mvn
    type: BuildInfo
    configuration:
      sourceArtifactory: kermit_art
      buildName: mvn_example_build
      buildNumber: 1
      
  - name: project_example_mvn
    type: GitRepo
    configuration:
      gitProvider: deepikaGithub
      path: deepikasl/project-examples
 
pipelines:
  - name: mvn_example_build_u18java
    steps:
      - name: mvn_build_u18java
        type: MvnBuild
        configuration:
          sourceLocation: ./artifactory-maven-plugin-example
          mvnCommand: clean install -f ./pom.xml
          configFileLocation: .
          configFileName: mvn-art-config
          nodePool: deepika_u16_node
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          inputResources:
            - name: project_example_mvn
          integrations:
            - name: kermit_art
        execution:
          onStart:
            - javac -version
            - mvn --version
      - name: publish_mvn
        type: PublishBuildInfo
        configuration:
          integrations:
            - name: kermit_art
          inputSteps:
            - name: mvn_build_u18java
          outputResources:
            - name: build_info_mvn
