resources:
  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      path: skylark05/npmHelloWorld
      gitProvider: github
  - name: helloworld_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: npm_example
      buildNumber: 1
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm-local
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
          integrations:
            - name: art
      - name: publish_npm
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: build_npm
          integrations:
            - name: art
      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: publish_npm
          integrations:
            - name: art
          outputResources:
            - name: helloworld_build_info
