resources:
  - name: npmHelloWorld_repo
    type: GitRepo
#     configuration:
#       path: deepikasl/npmHelloWorld
#       gitProvider: deepikaGithub
  - name: helloworld_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: npm_example
      buildNumber: 1
  - name: files
    type: FileSpec
    configuration:
      sourceArtifactory: art
      pattern: generic-local/*
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm-remote
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
            - name: files
          integrations:
            - name: art
      
