resources:
  - name: npmHelloWorld_repo
    type: GitRepo
    configuration:
      path: deepikasl/npmHelloWorld
      gitProvider: deepikaGithub
  - name: helloworld_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: deepika_artifactory
      buildName: npm_example
      buildNumber: 1
  - name: files
    type: FileSpec
    configuration:
      sourceArtifactory: deepika_artifactory
      pattern: deepika-promoted/*
      
pipelines:
  - name: npm_example
    steps:
      - name: build_npm
        type: NpmBuild
        configuration:
          repositoryName: npm-dev-local
          sourceLocation: .
          inputResources:
            - name: npmHelloWorld_repo
            - name: files
#           integrations:
#             - name: deepika_artifactory
      
